export const IMAGES = {
  socialSeal: require('./SocialSeal.svg').default,
  header_1: require('./header_1.png'),
  header_2: require('./header_2.png'),
  header_3: require('./header_3.png'),
  entrepreneur: require('./entrepreneur.png'),
  google: require('./google.png'),
  facebook: require('./facebook.png'),
  meta: require('./meta.png'),
  risks: require('./risks.png'),
  sales: require('./sales.png'),
  protect: require('./protect.png'),
  questions_1: require('./questions_1.png'),
  questions_2: require('./questions_2.png'),
  questions_3: require('./questions_3.png'),
  whatWeDo: require('./whatWeDo.png'),
  logo: require('./logo.svg').default,
  squad_1: require('./squad_1.png'),
  squad_2: require('./squad_2.png'),
  squad_3: require('./squad_3.png'),
  faq: require('./faq.png'),
  accelerate: require('./accelerate.png'),
};